### ISSUE TITLE
"Completed" checkmark

### ISSUE THREAD

**Issue by Sarge955** [MillenniumEarl/YAM#126]
Add an option to mark the current version of a game completed.
This would just be, more or less, a checkmark, so that you can see that you have completed all the content in the current version. This could be auto cleared when a new version is installed.

**Comment by MillenniumEarl** [comment]
Hi @Sarge955!

As written even in #127, I'm going to rewrite the application by implementing new features, unfortunately I don't know how to give you a precise date on when this will happen, certainly not in the short term (a few months at least).
