### ISSUE TITLE
"Comics" and "Animations" categories

### ISSUE THREAD

**Issue by Sarge955** [MillenniumEarl/YAM#127]
**Is your feature request related to a problem? Please describe.**
As far as I have experienced, there is no way to add anything from the "Comics" or "Animations" sections.

**Describe the solution you'd like**
Seperate sections for those categories, Due to the nature of them, they should not require a folder, but just a link to the post.
This should make it possible to add a post, and verify that you have seen the newest update. The should then be possible to "mark as read" so that they won't show a marker until next update.

**Describe alternatives you've considered**
I have tried using F95Watcher, which seems to do this without too much trouble. Although it would be nice to have this implemented in the same manager as the games.
The tool is located here: [https://f95zone.to/threads/f95-favorite-games-updates-v1-2-0.44538/](url)

**Comment by MillenniumEarl** [comment]
Hi @Sarge955!

This feature does not depend on the manager in itself but from the library I use to obtain data from the platform ([F95API](https://github.com/MillenniumEarl/F95API)).

In the last two weeks I was completely rewritten and I also added comic and animation support (I still have to fix the assets).

I don't have a exact date but I'm going to completely rewrite the manager, implementing new features and simplifying the code.
