### ISSUE TITLE
brackets mess with UnRen

### ISSUE THREAD

**Issue by ChaosDMNS** [MillenniumEarl/YAM#247]
The brackets in the version naming system [ ] messes with unren.bat all versions.

can't Decompile rpyc files without removing the brackets first. took me a while to figure out that is was the brackets. tried everything else first.

I don't know if the brackets mess with RenPy games when you play them. but unren doesn't work with brackets.

could we use ( ) instead? that works fine.

**Comment by MillenniumEarl** [comment]
I'll replace square brackets with rounded ones in the next version.
