### ISSUE TITLE
Set default browser to open links or add an option to copy the link

### ISSUE THREAD

**Issue by Shirouste2** [MillenniumEarl/YAM#80]
**Is your feature request related to a problem? Please describe.**
I don't want to open a porn website in my default browser

**Describe the solution you'd like**
It would be awesome if I could choose which browser I want to use for this application, or an option to copy the link

**Comment by MillenniumEarl** [comment]
I will start working on it as soon as possible. Meanwhile, all links (on the buttons) are draggable. For the moment this could be an alternative solution

**Comment by MillenniumEarl** [comment]
I've added a setting that allows you to choose whether to copy or open links in the default browser. It will be available in version 2.5.6
