### ISSUE TITLE
[2.5.5] Update message isn't formatted correctly.

### ISSUE THREAD

**Issue by KnuffelBeestje** [MillenniumEarl/YAM#87]
**Describe the bug**
The messagebox at the update message is using the GitHub format. And isn't displaying these formats correctly.

**To Reproduce**

1. Load up an older version of YAM that requires an update.
2. Look at the popup

**Expected behavior**
The description should be formatted correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/22412324/104185944-f831ed00-5415-11eb-9126-d2c86ec49fcb.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- App version: 2.5.5

**Comment by MillenniumEarl** [comment]
Thanks, it seems that the markdown text of the release changelog is not parsing correctly. I will try to correct it as soon as possible.
