### ISSUE TITLE
opening thread link not working properly in update window

### ISSUE THREAD

**Issue by silentnoodlemaster** [MillenniumEarl/YAM#93]
**Describe the bug**
When i go to click on "Open Thread" in the update dialog, nothing happens, 
electron logs `Check failed: chdir(current_directory) == 0`

but if i manually run `xdg-open <link>` (as electron does on linux) it works fine

the "Open Directory" button works normally

Does not affect the link on the game card

**Desktop:** 

- OS: Linux
- Version: archlinux 5.10.9-zen
- App version: 2.5.6

**Comment by MillenniumEarl** [comment]
Thanks!

Forgive me if I have not solved the problem but at the moment I am a little too busy irl
